### PR TITLE
move definition of cgadgetron target

### LINKED ISSUE #953: CMake error in cgadgetron
After including the headers (and libraries) in #952 we get this error

```
-- The Gadgetron toolboxes required for radial gridding were found. Non-cartesian encoding will be compiled.
-- Found CUDA: /usr/local/cuda (found version "10.0")
CMake Error at src/xGadgetron/cGadgetron/CMakeLists.txt:76 (target_include_directories):
  Cannot specify include directories for target "cgadgetron" which is not
  built by this project.
```

This is due to the fact that the `cgadgetron` target is defined after the `target_include_directory`

### PR DESCRIPTION
**Pull request by paskino**
closes #953

### CODE REVIEW

**Comment by paskino** [comment]
@KrisThielemans your force push in #951 moved the definition of `cgadgetron` target in the `CMakeLists.txt` after the `target_include_directories`, hence this error. Please do not force push on my branches.


This PR creates the target at the earliest occasion and beforre the `target_include_directories`.

**Comment by KrisThielemans** [comment]
> Please do not force push on my branches.

sorry. not my intention to overwrite your commits. In a hurry...

Please just fix this. I trust you

**Comment by paskino** [comment]
Of course. 

Unfortunately, there's a new error:

```bash
[ 98%] Linking CXX executable SYN_TEST_CPLUSPLUS
../xGadgetron/cGadgetron/libcgadgetron.a(gadgetron_x.cpp.o): In function `sirf::MRAcquisitionModel::set_up(std::shared_ptr<sirf::MRAcquisitionData>, std::shared_ptr<sirf::ISMRMRDImageData>)':
gadgetron_x.cpp:(.text+0x20a5): undefined reference to `vtable for sirf::RPEFourierEncoding'
../xGadgetron/cGadgetron/libcgadgetron.a(gadgetron_data_containers.cpp.o): In function `sirf::CoilImagesVector::calculate(sirf::MRAcquisitionData const&, int)':
gadgetron_data_containers.cpp:(.text+0x13353): undefined reference to `vtable for sirf::RPEFourierEncoding'
```

@evgueni-ovtchinnikov @johannesmayer  any idea?

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer stackoverflow suggests this might be caused by the absence of virtual destructor in `RPEFourierEncoding`.

@paskino how come you merged despite the build error - has it disappeared?

**Pull request merged**
