### PR TITLE
Implemented workaround enabling new Gadgetron to read old ISMRMRD acquisition data

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
Recent versions of Gadgetron fail to read ISMRMRD acquisition data generated by old ISMRMRD because of the line
```
<version>3</version>
```
in the acquisition data header XML.

This workaround simply makes method `MRAcquisitionData::read` ignore this line.

### CODE REVIEW

**Comment by johannesmayer** [comment]
The code seems to just cut out the `<version> ... <\version>` part, and I think that is correct.
What I find strange is that they check the version, but if no version is present, however, they don't complain, only if the wrong one is present.

**Comment by DANAJK** [comment]
Sorry, I don't know. There are some hints here as to what has changed:
https://github.com/ismrmrd/ismrmrd/releases

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans actually, the very idea of my workaround came to me when I noticed that David's acquisition data files `grappa2_*rep.h5` had headers without that troublesome version line

**Comment by KrisThielemans** [comment]
ok, well, what about checking the version number, if it's the same as the current ISMRMRD version, we keep it. If it's higher, we throw an error, if it's lower, we remove it and write a (very noticeable) warning. This would have to be documented in the User's Guide (and CHANGES)

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
ok, but I think the warning/error should be a bit more helpful really, like "ISMRMRD software version 4 is older than the version in the header (5). Failed to read file XXXX"

**Review by DANAJK — COMMENTED** [review]
I spent a while looking at this code and the title of this Issue, but it isn't clear to me which way around the error is thrown. If one of these things called 'header' refers to the .h5 file in ISMRMRD format, can that be more explicitly stated? If the other 'header' refers to the running software, something like "Input ISMRMRD file has version XX but software only able to read versions less than YY"

**Comment by evgueni-ovtchinnikov** [comment]
@DANAJK @KrisThielemans How about "Input ISMRMRD acquisitions file header is written in XML version XX, but the version of ISMRMRD used presently by SIRF supports XML version YY or less only"?

**Comment by DANAJK** [comment]
> @DANAJK @KrisThielemans How about "Input ISMRMRD acquisitions file header is written in XML version XX, but the version of ISMRMRD used presently by SIRF supports XML version YY or less only"?

Yes, that is clearer.

**Comment by KrisThielemans** [comment]
> > @DANAJK @KrisThielemans How about "Input ISMRMRD acquisitions file header is written in XML version XX, but the version of ISMRMRD used presently by SIRF supports XML version YY or less only"?
> 
> Yes, that is clearer.

Some suggested change:
"Input acquisition file was written in with ISMRMRD XML version XX, but the version of ISMRMRD used presently by SIRF supports XML version YY or less only"

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer how come my PR got lots of commits from your PR #980?

**Comment by KrisThielemans** [comment]
a bit weird. However, I don't think @johannesmayer has push access, so maybe you merged his version into yours at some point by mistake?

We can get rid of it by using interactive rebase (a bit dangerous), or merge #980 first.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans I remembered: 13 days ago I merged #980 onto `master`, which created conflicts between `master` and `qfix-xml`. I merged `master` onto `qfix-xml` and resolved conflicts. Safe to merge this PR then?

**Comment by KrisThielemans** [comment]
ok. I guess I'd recommend to do another merge of master here (as I see no merge commit for `master`) to be safe. of course, if you see locally that this didn't do anything, you can go ahead and merge this PR.

**Pull request merged**
