### PR TITLE
Test only SIRF tests and force output on travis

### PR DESCRIPTION
**Pull request by paskino**
Following https://github.com/SyneRBI/SIRF/pull/853#issuecomment-774037988 I suggest to run only SIRF tests and force output on travis.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I certainly agree to run only SIRF tests in the SIRF Travis, but I think useful to keep the gadgetron log to see why stuff failed.
Also, best to keep this travis as close as possible to the SIRF-Superbuild one.

Summary: I think only change needed is to say
```
cd builds/SIRF/build; ctest --verbose; test_fail=$?
```

**Comment by paskino** [comment]
In the original command, `test_fail` will be populated only in case of some test failure. 

```bash 
ctest --verbose V --output-on-failure; test_fail=$?
```

In the new command `test_fail` will be always populated, won't it? That's the reason I commented out all the gadgetron log section.

**Comment by KrisThielemans** [comment]
possibly there's some Travis trickery with the `| |` and subshells, but I cannot see the difference (aside from the fact that possibly I should have written `cd builds/SIRF/build && ctest --verbose; test_fail=$?` but I wouldn't know why that'd make any difference. In all of these, `test_fail` should be set to the exit value of `ctest`. no?

**Comment by paskino** [comment]
Oh yes, you are right. I had thought it'd have the output of the tests, which isn't true.

**Pull request merged**
