### PR TITLE
reset stir verbosity after niftypet and adjoint tests

### PR DESCRIPTION
**Pull request by rijobro**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
failure https://travis-ci.org/github/SyneRBI/SIRF/jobs/683415234#L23057
```
  File "/home/travis/build/SyneRBI/SIRF/src/xSTIR/pSTIR/tests/test_six_adjoint.py", line 24, in test_main
    original_verb = pet.get_verbosity()
TypeError: get_verbosity() missing 1 required positional argument: 'verbosity'
```

**Comment by KrisThielemans** [comment]
but what about the job failure above?

**Comment by rijobro** [comment]
That was sorted in the previous commit. Most recent travis builds were happy (or as happy as can be at the moment).

**Comment by KrisThielemans** [comment]
ok great. thanks!

**Pull request merged**
