### PR TITLE
Sorted out various issues with PET demos

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
## Changes in this pull request

* added missing `--non-interactive` option and skipping data displays in non-interactive mode
* added missing default output to `acf.hs` in `acquisition_sensitivity_from_attenuation.py`
* removed skipping listmode scripts by `run_all.py`
* sorted demos in `run_all.py` (pending more general solution to the execution order problem)
* corrected naming mismatch for some demos output files used as input for some other demos

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

### CODE REVIEW

**Review by KrisThielemans — APPROVED** [review]
I haven't run this, but all looks sensible. Feel free to merge

**Comment by evgueni-ovtchinnikov** [comment]
I had to change the scanning time interval in `reconstruct_from_listmode.py` from `(0,50)` to `(0,100)`, otherwise `scatter_estimation.py` complained that it expected `(0,100)` but got `(0,50)` - could not figure out how the former demo affects the latter (the only thing I can see is that the latter is executed after the former, but it does not help me much).

If this is ok, I will merge.

**Comment by KrisThielemans** [comment]
This is ok. I guess we were trying to save some time in not repeating stuff. Indeed, if we calculate/plot scatter from data with a different duration, things wouldn't be good, so it checks for that.

Would be useful to add a comment in the relevant demo saying that they need to run the other first (it might be there already of course), and that interval needs to be the same.

then go ahead

**Comment by evgueni-ovtchinnikov** [comment]
> Would be useful to add a comment in the relevant demo saying that they need to run the other first (it might be there already of course)

Yes it is there in `scatter_estimation.py`, so merging.

**Pull request merged**
