### PR TITLE
Auto sort by time

### LINKED ISSUE #949: error in `CoilSensitivityData.calculate` in SIRF-Exercises
When my SIRF is compiled with ISMRMR 1.4.1, running `SIRF-Exercises/Introductory/acquisition_model_mr_pet_ct.ipynb` gave
```
mr_acq = mr.AcquisitionData(os.path.join(examples_data_path('MR'),'grappa2_1rep.h5'))
preprocessed_data = mr.preprocess_acquisition_data(mr_acq)

csm = mr.CoilSensitivityData()
csm.smoothness = 50
csm.calculate(preprocessed_data)
```
This gives me an error
```
error: ??? "'binary algebraic operations cannot be applied to unsorted data'
```
@ckolbPTB do you see this as well?

### PR DESCRIPTION
**Pull request by johannesmayer**
Fixes #949.

Both the `MRAcquisitionData::read()` function and the `AcquisitionsProcessor::get_output()` return sorted containers now.
`MRAcquisitionModel` and `CoilsensitivityData` basically always need sorted data so this takes away the responsibility from the user to call `sort()` in (for her/her arbitrary places).

### CODE REVIEW

**Comment by KrisThielemans** [comment]
thanks. @evgueni-ovtchinnikov what do you think?

@johannesmayer can you add somethng to `CHANGES.md`? (with [ci skip]')

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer also after forward projection, I suppose? Or is it already taken care of?

BTW before sorting, I would check whether the data has not been sorted already.

**Review by evgueni-ovtchinnikov — APPROVED** [review]
please see my comment re forward projection and reconstruction and checking whether sorted already

**Comment by johannesmayer** [comment]
> @johannesmayer what about forward projection and reconstruction? Or is it already taken care of?

forward and backward projection will throw an exception if the data is not sorted already.

> BTW before sorting, I would check whether the data has not been sorted already.

good idea I will put it in

**Comment by KrisThielemans** [comment]
great. what about squash-merging this? As history went a bit back and forth

**Pull request merged**
