### PR TITLE
Add MR cpp tests

### PR DESCRIPTION
**Pull request by johannesmayer**
I set up a test environment for the xGadgetron code on the cpp level, so I can write tests for the inclusion of trajectory and encoding models.

I just went along analogously to the other CMake directories who had tests in them.

If the copyright tag is wrong please let me know.

### CODE REVIEW

**Comment by johannesmayer** [comment]
Shoot, Richard merged his PR right before I submitted mine, so now I have not merged that stuff in this branch. But I already did do it now and send it to my fork. 

How can I update this PR to the current version of the branch?

**Comment by rijobro** [comment]
Looks like you successfully merged master in here. Any outstanding questions? Does the ctest work?

**Comment by johannesmayer** [comment]
> Looks like you successfully merged master in here. Any outstanding questions? Does the ctest work?

How do I check that? What is the ctest?

**Comment by rijobro** [comment]
With the line `ADD_TEST(NAME MR_TEST_CPLUSPLUS...` you created a ctest called `MR_TEST_CPLUSPLUS`. You should be able to see it with:

```
cd build_directory
cmake .
make 
ctest -N
```

When you run `ctest -N`,  you should see a list of all of our ctests. 

You should be able to run your ctest with:
```
ctest -VV -R MR_TEST_CPLUSPLUS
```

Running `ctest` with `-R` will run all tests matching the given pattern (in this case `MR_TEST_CPLUSPLUS`). Using the `-VV` means a verbose output.

**Comment by johannesmayer** [comment]
yo this passes 💯

**Comment by rijobro** [comment]
great. now make it actually test something ;)

**Comment by KrisThielemans** [comment]
@johannesmayer are you still working on this? Maybe it's superseded by other things?

**Comment by johannesmayer** [comment]
I am not working on this branch any more. However, the branch I am working on for the MR reconstruction uses these tests on cpp level. So I would say superseded?

**Comment by KrisThielemans** [comment]
Ok. I guess you should close it then.

**Pull request closed without merging**
