### PR TITLE
[TRAVIS] drop xenial and python2, test focal

### LINKED ISSUE #854: travis fails with pip install errors
https://travis-ci.org/github/SyneRBI/SIRF/jobs/755929284#L1407
```
$ $PY_EXE get-pip.py --user
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/tmp/tmphiad2ac9/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```
It fails with this error on
- Xenial python 2
- Xenial python 3
- bionic python 2

`pip` 20 was going to drop support for `python2` in January, but possibly the xenial python3 is too old as well...

### PR DESCRIPTION
**Pull request by KrisThielemans**
- Ubuntu 16.04 has more and more trouble, including with pip installation.
- python2 is no longer supported by many packages
- we really need to test with more recent Ubuntu, so using 20.04 LTS (focal)

In addition, some improvements:
- install some apt packages only on certain jobs
- give jobs names

As focal's CMake is more recent than 3.13, it would be dangerous to use the older version.
Therefore just relying on the default CMake (which is 3.10 on bionic so should be fine)

Fixes #854

### CODE REVIEW

**Comment by KrisThielemans** [comment]
`focal` uses gcc-9 as default but that doesn't work yet due to dependencies. See https://github.com/SyneRBI/SIRF-SuperBuild/issues/413. See testing now with gcc-8.

**Comment by KrisThielemans** [comment]
I have a problem with the APT package install. In the current status, the first [`focal` job](https://travis-ci.org/github/SyneRBI/SIRF/jobs/756070265) runs fine, meaning that it installed `g++-8` and `libinsighttoolkit4-dev` as I ask. However, the [second `focal` job](https://travis-ci.org/github/SyneRBI/SIRF/jobs/756070266) doesn't install these, and therefore fails. Do I have my `.travis.yml` syntax wrong?

@casperdcl if you could have a quick look, I'll be eternally grateful!

**Comment by KrisThielemans** [comment]
thanks @casperdcl but that didn't work. I had tried that before, but as `g++` depends on `gcc` for `APT`, I don't think adding `gcc` does anything at all. In fact, as you can see [in the apt lines of the job](https://travis-ci.org/github/SyneRBI/SIRF/jobs/756102768#L173), Travis ignored all 3 dependencies that I added (`g+-8, boost and ITK). I have no idea why.

**Comment by casperdcl** [comment]
ah just looked at the diff - the issue is https://stackoverflow.com/questions/19502522/extend-an-array-in-yaml

**Comment by KrisThielemans** [comment]
aw. that looks terribly ugly. Oh well. I might then revert it to the previous way of listing all packages at the top, even if we don't need them.

I guess we have the same problem in the [SuperBuild](https://github.com/SyneRBI/SIRF-SuperBuild/blob/f5abe5b75fcadc8144082eb2ca84d1cb26f6a167/.travis.yml#L86-L87) where I stole this from. It just so happens that there we didn't see it as `g++-6` is listed in `addons_apt_packages` as well.

**Comment by KrisThielemans** [comment]
what about the solution on https://github.com/travis-ci/travis-ci/issues/3505

**Comment by casperdcl** [comment]
ah so they do indeed support flattening, it just isn't documented. Sure...

**Comment by KrisThielemans** [comment]
thanks for doing that! 

By the way, amazingly even the previous commit [failed for the 2nd job] (https://travis-ci.org/github/SyneRBI/SIRF/jobs/756234100#L173). Probably some obscure interpretation of what we had. Let's hope for the best now!

**Comment by KrisThielemans** [comment]
nope. it keeps failing the 2nd job as it doesn't `apt install` what we ask it
https://travis-ci.org/github/SyneRBI/SIRF/jobs/756246287#L173. It works fine for the first one though: https://travis-ci.org/github/SyneRBI/SIRF/jobs/756246286#L170

something else presumably. I'm looking at https://config.travis-ci.com/explore for validation, which gives some errors.

**Comment by casperdcl** [comment]
yes well it does help actually using the same config keys (`apt != addons.apt`)

**Comment by KrisThielemans** [comment]
oops. sorry!

**Comment by KrisThielemans** [comment]
success! they're going through. Now hoping that the tests don't fail...

**Comment by KrisThielemans** [comment]
great. I've sinned and manipulated history to clean things up a bit. If you mind, feel free to restore and merge, else just merge (or I'll do it tomorrow).

thanks for your help!

**Pull request merged**
