### PR TITLE
add __call__ as alias to value

### LINKED ISSUE #930: Add __call__ method to PET ObjectiveFunction
Add `__call__` as alias to [`value`](https://github.com/SyneRBI/SIRF/blob/master/src/xSTIR/pSTIR/STIR.py#L2085)

### PR DESCRIPTION
**Pull request by paskino**
closes #930

### CODE REVIEW

**Comment by ashgillman** [comment]
Sorry for off-topic

How did you make a PR "draft"? Very useful feature.

**Comment by paskino** [comment]
@ashgillman it's in the interface, when you create the PR on the right column (high) you have something like "not ready yet, convert to draft"

**Comment by KrisThielemans** [comment]
looks like an indentation error

**Comment by paskino** [comment]
I'm adding an unit test

**Pull request merged**
