### PR TITLE
Interface compute_kernelised_image into SIRF

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**

### CODE REVIEW

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda SIRF interface to STIR's `compute_kernelised_image` seems to work now (see `hkem_reconstruction.py` on SIRF branch `kernelised-image`), but I am afraid I cannot properly test it - could you, please?

**Comment by danieldeidda** [comment]
> @danieldeidda SIRF interface to STIR's `compute_kernelised_image` seems to work now (see `hkem_reconstruction.py` on SIRF branch `kernelised-image`), but I am afraid I cannot properly test it - could you, please?

HI thanks a lot! yes I am going to test it and let you know ASAP. Thanks!

**Comment by danieldeidda** [comment]
I am trying to commit a change to the hkem_reconstruction.py file but it seems I don't have permission

**Comment by evgueni-ovtchinnikov** [comment]
@danieldeidda try committing again please and let me know whether you succeeded

**Comment by danieldeidda** [comment]
now it worked but it created a new PR (#1165),  with those changes this PR can also be approved

**Comment by KrisThielemans** [comment]
thanks @danieldeidda , so merge this one first and #1165 afterwards?

**Pull request merged**
