### PR TITLE
Backwards compatibility of STIR's shared_ptr<const ExamInfo>

### PR DESCRIPTION
**Pull request by rijobro**
Addresses problems mentioned in https://github.com/SyneRBI/SIRF/pull/619

### CODE REVIEW

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov Can you give this one a go and let me know if it solves your problem?

**Comment by rijobro** [comment]
I don't understand, you had to make some changes on top of this PR? Because Travis isn't happy, so if you have those corrections, feel free to push.

**Comment by rijobro** [comment]
@KrisThielemans - is the error below because `get_exam_info_sptr` used to return a raw pointer but now returns a shared pointer?

```
/home/travis/build/SyneRBI/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:600:83: error: no matching function for call to â€˜stir::VoxelsOnCartesianGrid<float>::VoxelsOnCartesianGrid(std::shared_ptr<const stir::ExamInfo>, const stir::ProjDataInfo&)â€™
    _data.reset(new Voxels3DF(ad.get_exam_info_sptr(),*ad.get_proj_data_info_sptr()));
```

**Comment by evgueni-ovtchinnikov** [comment]
I just tried with three occasions locally to see if the errors would disappear. I thought you would merge your branch on master and then I would pull and get all the corrections?

**Comment by rijobro** [comment]
Ah, I thought you would checkout this branch, but it sounds like you did the same thing manually.

**Comment by evgueni-ovtchinnikov** [comment]
This is a branch of your fork, and I remember getting into trouble at the last Hackathon when dealing with branches of Johannes fork, so I would rather wait until you merge on master.

**Comment by KrisThielemans** [comment]
@rijobro, I think my commit is a bit cleaner than yours. I've also resolved the above compilation problem. Have a look please.

**Pull request merged**
