### PR TITLE
Fix flag checking for CSM computation

### PR DESCRIPTION
**Pull request by johannesmayer**
This is a fix of the shift of the last CSM fix into the C++ layer (I don't know what the hell I had tested there).

The strategy is the same:
- `CoilImagesVector::calculate(MRAcquisitionData& )` extracts a subset of the acquisitions that carry a flag that marks them as coil calibration data.
- if none of the acquisitions has that flag, then all acquisitions are used.

The problem with the current code is that the `ISMRMRD::Acquisition::isFlagSet()` method behaves unexpectedly and I don't know why. I will open an issue for it. Right now I use a different approach to check for which flags are set.

New things:

*I wrote a method `CoilImagesVector::extract_calibration_data` 
*I check if the flags are set without the `ISMRMRD` methods

### CODE REVIEW

**Comment by KrisThielemans** [comment]
test failures I'm afraid. @johannesmayer can you fix them? @evgueni-ovtchinnikov can you then have a quick look and merge? We can fix behaviour afer 3.1-rc.1 (if necessary!)

**Comment by johannesmayer** [comment]
The failures are strange complaining about dependencies :
```
# SIRF external dependencies
apt-get update -qq
E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' no longer has a Release file.
```

**Comment by johannesmayer** [comment]
After merging master again it seems to go past the dependencies now.

**Comment by KrisThielemans** [comment]
probably a GHA issue. let's see

**Comment by johannesmayer** [comment]
ok went through

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov ok to merge? Just do so!

**Pull request merged**
