### PR TITLE
fix fill for tensor images

### PR DESCRIPTION
**Pull request by rijobro**
fixes https://github.com/SyneRBI/SIRF/issues/672

### CODE REVIEW

**Comment by rijobro** [comment]
@ALEXJAZZ008008 could you give this a go and let me know?

**Comment by rijobro** [comment]
Merging as this solves it for me and travis is happy. @ALEXJAZZ008008 let me know if it creates a problem for you.

**Comment by ALEXJAZZ008008** [comment]
Sorry about the delay, I thought I would just verify that master (and hence this) work fine for me now. Thank you!

**Comment by rijobro** [comment]
Great, thanks.

**Pull request merged**
