### PR TITLE
use const ExamInfo

### PR DESCRIPTION
**Pull request by rijobro**

### CODE REVIEW

**Comment by rijobro** [comment]
@AnderBiguri this PR should fix things for you

**Comment by AnderBiguri** [comment]
Just to add info here, maybe it can help @evgueni-ovtchinnikov :+1: 

@rijobro Did this because using the previous commit + the `rijobro/STIR/GPU-projector` was giving me the following error when building SIRF:

```
[  9%] Building CXX object src/Synergistic/cSyn/CMakeFiles/csyn.dir/utilities.cpp.o
In file included from /home/anderbiguri/SIRF/build/sources/SIRF/src/Synergistic/cSyn/utilities.cpp:33:0:
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h: In member function 'std::shared_ptr<sirf::PETAcquisitionData> sirf::PETAcquisitionData::single_slice_rebinned_data(int, int, int, bool, int)':
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:165:59: error: no matching function for call to 'sirf::PETAcquisitionData::same_acquisition_data(std::shared_ptr<const stir::ExamInfo>, std::shared_ptr<stir::ProjDataInfo>&)'
     (data()->get_exam_info_sptr(), out_proj_data_info_sptr));
                                                           ^
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:143:31: note: candidate: virtual sirf::PETAcquisitionData* sirf::PETAcquisitionData::same_acquisition_data(std::shared_ptr<stir::ExamInfo>, std::shared_ptr<stir::ProjDataInfo>) const
   virtual PETAcquisitionData* same_acquisition_data
                               ^~~~~~~~~~~~~~~~~~~~~
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:143:31: note:   no known conversion for argument 1 from 'std::shared_ptr<const stir::ExamInfo>' to 'std::shared_ptr<stir::ExamInfo>'
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h: In member function 'std::shared_ptr<stir::ExamInfo> sirf::PETAcquisitionData::get_exam_info_sptr() const':
/home/anderbiguri/SIRF/build/sources/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:266:37: error: could not convert 'stir::ExamData::get_exam_info_sptr()' from 'std::shared_ptr<const stir::ExamInfo>' to 'std::shared_ptr<stir::ExamInfo>'
    return data()->get_exam_info_sptr();
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
src/Synergistic/cSyn/CMakeFiles/csyn.dir/build.make:62: recipe for target 'src/Synergistic/cSyn/CMakeFiles/csyn.dir/utilities.cpp.o' failed
make[6]: *** [src/Synergistic/cSyn/CMakeFiles/csyn.dir/utilities.cpp.o] Error 1
CMakeFiles/Makefile2:1949: recipe for target 'src/Synergistic/cSyn/CMakeFiles/csyn.dir/all' failed
make[5]: *** [src/Synergistic/cSyn/CMakeFiles/csyn.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/SIRF.dir/build.make:118: recipe for target 'builds/SIRF/stamp/SIRF-build' failed
make[3]: *** [builds/SIRF/stamp/SIRF-build] Error 2
CMakeFiles/Makefile2:564: recipe for target 'CMakeFiles/SIRF.dir/all' failed
make[2]: *** [CMakeFiles/SIRF.dir/all] Error 2
CMakeFiles/Makefile2:576: recipe for target 'CMakeFiles/SIRF.dir/rule' failed
make[1]: *** [CMakeFiles/SIRF.dir/rule] Error 2
Makefile:298: recipe for target 'SIRF' failed
make: *** [SIRF] Error 2
```

**Comment by rijobro** [comment]
Hm this comes about from trying to use the safer STIR functionality, whilst preserving backwards compatibility. It seems that `create_shared_clone`, which sits in `ExamInfo.h` in STIR has only recently been marked `const` ([link](https://github.com/UCL/STIR/commit/29133a3ffa690b444894b4392aa710e8bb33a42e#diff-ef9349d0e61a4e1f7ff01b445383ea00)), which explains the error you're seeing.

I think the only solution therefore is to avoid `ExamInfo::create_shared_clone` in SIRF. Instead we should use something like `stir::shared_ptr<stir::ExamInfo>(new stir::ExamInfo(ei_const_sptr));`. 

@KrisThielemans, that ok with you?

**Comment by KrisThielemans** [comment]
yes indeed, i just came to the same conclusion. It was essentially a problem in previous `ExamInfo::create_shared_clone`. i think your solution is good (it's doing the same thing anyway), except that you need an extra `*` :-)

It seems that Travis was green because it's still running with STIR `master`
https://github.com/SyneRBI/SIRF/blob/685469981611d1beab84bc98df409e706e9e4300/.travis.yml#L62
See https://github.com/SyneRBI/SIRF/issues/366

@rijobro, can you get rid of the hard-wired tag please? Could do it in the same PR as the above fix (2 different commits).

**Comment by KrisThielemans** [comment]
@ALEXJAZZ008008 this will probably explain your problems as well

**Pull request merged**
