### PR TITLE
disable get_inverse in NonRigidTransformation for Visual Studio

### LINKED ISSUE #665: Build errors on Windows 10
building SIRF `master` on my Windows 10 laptop produces lots of error messages like this one:
```
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDeformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDeformation@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDeformation@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDeformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDeformation@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDeformation<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDeformation@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDisplacement<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDisplacement@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_nr(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_nr@?$NiftiImageData3DDisplacement@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
10>sirf_inverse_transform.obj : error LNK2019: unresolved external symbol "protected: virtual class sirf::NiftiImageData3DDisplacement<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDisplacement@M@sirf@@MEBAPEAV12@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z) referenced in function "public: class sirf::NonRigidTransformation<float> * __cdecl sirf::NiftiImageData3DDisplacement<float>::get_inverse_impl_vtk(class std::shared_ptr<class sirf::NiftiImageData<float> const >)const " (?get_inverse_impl_vtk@?$NiftiImageData3DDisplacement@M@sirf@@QEBAPEAV?$NonRigidTransformation@M@2@V?$shared_ptr@$$CBV?$NiftiImageData@M@sirf@@@std@@@Z)
```

### PR DESCRIPTION
**Pull request by KrisThielemans**
This is a horrible work-around for a compilation problem.

Fixes #665

### CODE REVIEW

**Comment by evgueni-ovtchinnikov** [comment]
What is the correct procedure for pulling from a fork? I did `git pull <fork> <branch>` to get Deidda KOSMAPOSL branch and ended up in a complete mess - wasted half a day before realizing that my origin has become `https://github.com/danieldeidda/STIR` (same thing happened on our last Hackathon when I pulled Johannes branch, but I forgot about it - too many things happened in between).

**Comment by rijobro** [comment]
`git fetch --all && git checkout WorkAroundVSNRT` should be fine. You'll have to make sure you have a clean tree first. Check with `git status`, and potentially stash any changes with `git stash`.

**Comment by KrisThielemans** [comment]
In that situation you want to avoid `pull`. The following should work
```sh
git fetch <fork>
git checkout <branch>
```
This will create a local branch with name `<name>`, syncing with `<fork>/<branch'. Presumably it'll fail if you have already branch with that name (or 2 remotes). 

Alternatively, you could do
```sh
git checkout <fork>/<branch>
```
which will leave you in detached HEAD state, and you can then create a local branch from there.

None of this merges. (`git pull` = `git fetch; git merge`)

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov if this PR works for you, please merge.

**Comment by evgueni-ovtchinnikov** [comment]
thanks, but will it not change my origin (as previously happened with Johannes and Daniel forks)?

**Comment by KrisThielemans** [comment]
Nothing of this changes the URL of any remotes of course. So `origin` will still point to wherever it was.

It will set the "upstream" branch of `<branch>` to `<fork>/<branch>`.  However, this is a branch-specific thing, so if you do `git checkout master` (or whatever other branch), it will go back to what it was. You can check with `git branch -vv`. https://devconnected.com/how-to-set-upstream-branch-on-git/ seems useful

**Comment by evgueni-ovtchinnikov** [comment]
Builds ok, only a new (or perhaps unnoticed before) problem emerged: MATLAB files in `matlab\+mSTIR` etc. do not get updated (VS claims they are up-to-date when installing). Python files are updated ok.

Should I merge anyway, as this seems to be a separate (cmake?) issue?

**Comment by KrisThielemans** [comment]
Certainly doesn't have anything to do with this, so I'll merge.

I'd have thought that if it claims they're up-to-date that they are, but you never know... If so, please create a different issue (SIRF or SIRF-SuperBuild as appropriate)

**Comment by KrisThielemans** [comment]
OSX jobs on Travis timed-out in the tests. I've restarted them, but as this fix did not fall over during the compilation, I'll merge.

**Pull request merged**
