### PR TITLE
Randoms support for GE Signa

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
addresses #137

### CODE REVIEW

**Review by KrisThielemans — COMMENTED** [review]
I had a quick look. Seems alright. 2 comments:
- There are some changes here related to STIR changes using `shared_ptr<const ProjDataInfo>` etc. It would be far better to change SIRF signatures to use that as well, e.g.
```c++
PETAcquisitionDataInMemory(stir::shared_ptr<const stir::ExamInfo> sptr_exam_info,
			stir::shared_ptr<const stir::ProjDataInfo> sptr_proj_data_info)
```
as opposed to `stir::shared_ptr<stir::ProjDataInfo> sptr_proj_data_info`. Potentially it needs a some checks for STIR 4.x then, but hopefully not.

- I guess the changes in test_one.py and src/xSTIR/pSTIR/tests/tests_one.txt are not really related to this PR?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans thanks for your comments, replying respectively:
* I tried something that did not work and reversed changes but apparently not in this line, sorry.
* No, the errors that forced me to drop some tests from `tests_one.py` lest Travis goes red have nothing to do with this PR

BTW, some Travis runs seem to still get `Projdata`.

**Comment by KrisThielemans** [comment]
> BTW, some Travis runs seem to still get Projdata.

sorry. I merged this on STIR `master`, but we need it  on `release_4` as well of course. Will do that now and then try to restart the PR Travis job (I won't bother with the branch job)

**Comment by KrisThielemans** [comment]
for whatever reason I cannot restart the Travis jobs. Can you commit something else and push? could be some doc improvement, for instance update `CHANGES.md`

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
yeah. compilation problems with the STIR 4.x builds.

However, we should keep the SIRF interface side to use `shared_ptr<const>` now, and fix the compilations. Otherwise, we're going to have backwards incompatible changes in SIRF quite soon.

e.g.
https://github.com/SyneRBI/SIRF/blob/2ea29cb751b5280734c9943a60686c2719d3b662/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h#L92-L93
should become
```c++
#if STIR_VERSION >= 50000
			stir::ProjDataInterfile(sptr_exam_info, sptr_proj_data_info,
			filename, std::ios::in | std::ios::out | std::ios::trunc),
#else
                       // ugly work-around
			stir::ProjDataInterfile(sptr_exam_info->create_shared_clone(), sptr_proj_data_info->create_shared_clone(),
			filename, std::ios::in | std::ios::out | std::ios::trunc),
#endif
```
or whatever (not sure if the above will compile with STIR 4,x). I'm afraid you'll have to checkout a STIR `release_4` version (could do it in a separate build directory of course).

sorry

**Comment by KrisThielemans** [comment]
Great. All jobs succeed except https://travis-ci.com/github/SyneRBI/SIRF/jobs/491703373 which failed with the occasional Gadgetron error, unrelated to this PR.

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
feel free to merge! (delete the branch)

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans All Travis builds now succeeded, and all tests but one (usual `Bad file descriptor` error) too - ok to merge?

**Comment by KrisThielemans** [comment]
yes!

**Pull request merged**
