### PR TITLE
Wrap gadgets for better CINE reconstruction images

### PR DESCRIPTION
**Pull request by johannesmayer**
## Changes in this pull request
I wrapped some gadgets that when used in a gadget chain can improve CINE reconstruction image quality.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [ ] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@johannesmayer can you merge master in here again just to check? Should then be good to merge. Thanks!

**Comment by KrisThielemans** [comment]
I've merged `master`. Checks in progress.

@johannesmayer or @evgueni-ovtchinnikov can you update `CHANGES.md` and possibly users guide if gadgets are listed there?

**Comment by KrisThielemans** [comment]
@ckolbPTB maybe you can add something to `CHANGES.md` and other doc?

**Comment by KrisThielemans** [comment]
@ckolbPTB @johannesmayer could you check this one after ISMRM? We hope to release 3.5 quite soon now (unless we find anything that breaks).

**Comment by KrisThielemans** [comment]
thanks! @evgueni-ovtchinnikov how do people know which Gadgets are available?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans documentation on the gadgets used by SIRF is in `ReferenceManual`'s section `Classes::Class Index::Gadget`, and brief descriptions are in `UserGuide` Section 6.2.

**Comment by KrisThielemans** [comment]
@thanks. @ckolbPTB @johannesmayer could you then please update the doc as well? We're not qualified really... sorry

**Comment by ckolbPTB** [comment]
I updated the UserGuide. Do I need to add something somewhere else too?

By the way, the UserGuide seems to only cover very few gadgets which are available in SIRF. Might need some more thorough updates...

**Comment by KrisThielemans** [comment]
Thanks!

@evgueni-ovtchinnikov feel free to merge. Can you then also create an issue for documenting more gadgets such that we don't forget?

**Review by KrisThielemans — APPROVED** [review]

**Pull request merged**
