### PR TITLE
Add warning to stir.show()

### PR DESCRIPTION
**Pull request by AnderBiguri**
stir.show() will silently do nothing if you accidentally give out of index slice. 

Did it with print to avoid importing more  modules, but can change that to proper warning modules.

### CODE REVIEW

**Review by KrisThielemans — COMMENTED** [review]
Would it not be better to raise `IndexError` aside from just returning? @evgueni-ovtchinnikov, is there a reason we don't?

Ideally we add a check on the `tof` index as well

**Comment by AnderBiguri** [comment]
Sounds good to me, did not added error simply because I thought there may be a reason to just return and not crash. Happy to change whatever, let me know,

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov could you tell us if we can throw an exception ? @AnderBiguri, once we know, can you merge `master` in here? Travis should now work

**Comment by AnderBiguri** [comment]
Sure. Just let me know what you want the code to do and I'll merge master+commit.

**Comment by evgueni-ovtchinnikov** [comment]
yes, raising `IndexError` is a good idea

**Pull request merged**
