### PR TITLE
Fix appending .h5 instead of overwriting issue

### LINKED ISSUE #1055: MR tests write .h5 files and append to existing files
Our `MRAcquisitionData::write()` will always append to existing files. Some MR cpp tests write .h5 files to disc.

Upon repeated local running of the tests during the development of something new this leads to that at some point the files are too large and cryptic errors appear about .h5 files.

Should we stop writing them in the tests?

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
fixes #1055

### CODE REVIEW

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer please test on acquisition data (tested on image data only)

**Comment by johannesmayer** [comment]
For the tests it didn't build for some siemens-to-ismrmrd reason, at least on my VM the C++ tests don't write to the same file any more.

**Comment by KrisThielemans** [comment]
I think I've fixed the siemens_to_ismrmrd problem (we were running its `master`). in any case unrelated.

**Comment by KrisThielemans** [comment]
So, this isn't just a change to the tests, but actually any writing will no longer append. correct? That's fine for me, but I would prefer to document this in `CHANGES.md`. Then feel free to merge.

**Pull request merged**
