### PR TITLE
Pdim axpby

### PR DESCRIPTION
**Pull request by rijobro**
Requires https://github.com/SyneRBI/SIRF/pull/688 and https://github.com/UCL/STIR/pull/557.

### CODE REVIEW

**Comment by rijobro** [comment]
Running the following code:
```
for i in range(10):
    out.axpby(1,2,out)
    out.axpby(1,2,out,out)
```
Sees a dramatic increase in speed when comparing new code to old - 2.85 vs 46.6 s!

**Comment by rijobro** [comment]
```
In [1]: import sirf.STIR as pet                                                                                                                               

In [2]: pet.AcquisitionData.set_storage_scheme("memory")                                                                                                      

In [3]: a = pet.AcquisitionData('EM_g1.hs')                                                                                                                   

INFO: Setting energy window keys as in STIR3.0

In [4]: a.fill(1)                                                                                                                                             
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-ded0ac23c507> in <module>
----> 1 a.fill(1)

~/Documents/Code/SIRF-SuperBuild/Install/python/sirf/STIR.py in fill(self, value)
    735         assert self.handle is not None
    736         if self.read_only:
--> 737             raise error('Cannot fill read-only object, consider filling a clone')
    738         if isinstance(value, numpy.ndarray):
    739             if value.dtype is numpy.dtype('float32'):

error: ??? 'Cannot fill read-only object, consider filling a clone'
```

**Comment by rijobro** [comment]
@KrisThielemans - These PRs will fail for `DEVEL_BUILD=OFF` since the required features are only available on STIR `master` (well, `release_4`). Thoughts?

**Comment by KrisThielemans** [comment]
>  These PRs will fail for `DEVEL_BUILD=OFF` since the required features are only available on STIR `master` (well, `release_4`). Thoughts?

I'd recommend updating the SIRF-SuperBuild `STIR_TAG` to the tag on `release_4` . Obviously, can only do that after 2.2 is out. So... a PR on the SuperBuild.

**Pull request merged**
