### PR TITLE
Detect CMake version and use remove or rm accordingly

### LINKED ISSUE #1069: CMake Error: cmake version 3.13.4 in GENERATE_SIMULATED_TESTDATA
Running 

```
docker build --build-arg BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DBUILD_CIL=ON" --target sirf . 
```
I get the following error. 

```
CMake Error: cmake version 3.13.4
Usage: /opt/cmake-3.13.4-Linux-x86_64/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files file1 file2 - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
  create_symlink old new    - create a symbolic link new -> old

make[5]: *** [src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA] Error 1
src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA.dir/build.make:57: recipe for target 'src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA' failed
CMakeFiles/Makefile2:379: recipe for target 'src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA.dir/all' failed
ESC[91mmake[4]: *** [src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by paskino**
Fix #1069

### CODE REVIEW

**Comment by paskino** [comment]
CMake that this GHA uses is [3.22](https://github.com/SyneRBI/SIRF/runs/5536048000?check_suite_focus=true#step:5:24)

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
There's an `rm` below as well. Also, repetition is rather ugly.

I wonder though, @johannesmayer @evgueni-ovtchinnikov shouldn't/couldn't`GENERATE_SIMULATED_TESTDATA` and `PROCESS_SIMULATED_TESTDATA` be merged into 1?

I'll do a separate PR...

**Comment by KrisThielemans** [comment]
This seems to do the job as far as deleting/copying files, but I get a local failure due to numerical tolerance
```
2/20 Test  #2: MR_TESTS_PYTHON .........................***Failed   18.36 sec
Started reading acquisitions from /home/sirfuser/devel/install/share/SIRF-3.1/data/examples/MR/simulated_MR_2D_cartesian.h5
0%..10%..20%..30%..40%..50%..60%..70%..80%..90%..100%..
<snip>
ERROR: test2.test_main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/data/devel/SIRF/src/xGadgetron/pGadgetron/tests/test2.py", line 45, in test_main
    test.check(complex_images.norm() / input_norm)
  File "/home/sirfuser/devel/install/python/sirf/Utilities.py", line 312, in check
    self.check_if_equal_within_tolerance(expected, value, abs_tol, rel_tol)
  File "/home/sirfuser/devel/install/python/sirf/Utilities.py", line 346, in check_if_equal_within_tolerance
    raise ValueError(msg)
ValueError: +++ test 1 failed: expected 6.701, got 6.719 (tolerance 0.0134)
```
Seems to me we need to increase our tolerance a bit more. @johannesmayer, do you agree?

**Comment by paskino** [comment]
This seems to work in docker.

**Comment by paskino** [comment]
I would merge this.

**Pull request merged**
