### PR TITLE
Expose more AcquisitionData functionality

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
Exposes more AcquisitionData functionality

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@johannesmayer is this ready and/or needed and/or superseded?

**Comment by johannesmayer** [comment]
This is from the Hackathon when we were in England, I thought this had been merged. I have not worked on this any more.

**Comment by rijobro** [comment]
closing in that case

**Comment by KrisThielemans** [comment]
@johannesmayer @rijobro not sure now if this should have been closed or merged?

**Comment by johannesmayer** [comment]
I took a look into the code on master and I think this was already merged somewhere else from another PR.

**Pull request closed without merging**
